---
editor_options: 
  markdown: 
    wrap: 72
---

# Pricing Games

## Replication

$$\begin{bmatrix} 
11 \\ 11
\end{bmatrix}$$


상품의 가격은 어떻게 결정되는가라는 질문에 많은 사람들은 경제학의 수요곡선과 공급 곡선을 떠올리며, 수요와 공급이 만나는 점에서 가격이 결정된다고 말할 것이다. 맞는 이야기이다. 하지만 파생상품의 세계에서는 이와는 다른 논리를 이용하여 상품의 가격이 결정되는 과정을 설명할 수
있다. 


본 장의 목적은 경제학의 수요와 공급 법칙에 의하여 결정되는 가격이라는 것을 다른 논리를 이용하여 설명할 수 있으며, 궁극적으로 이 논리가 파생상품의 가격식을 유도하는 기본이 됨을 파악하는데 있다. 물론 서로 다른 논리에 의하여 결정되는 가격이라 하더라도 그 값은 서로 같아야 한다. 이러한 가격을 우리는 흔히 균형 가격, 합리적 가격 또는 no arbitrage price라 부른다. no arbitrage가 무엇인가는 본 장에 설명할 것이다.


이러한 논리를 전개시키기 위하여는 당연히 가정이 필요하다. 여기서 필요한 가정은 소비자의 효용함수가 어떠한 모양이라던지, 공급자에게는 규모의 경제가 적용된다라던지와 같은 경제학의 심오한 가정이 아니라 우리가 쉽게 받아들일 수 있는 간단한 가정이다. 물론 다음 단락에서 명시하는 2개의 가정 이외에도 경제학에서 흔히 사용되는 세금이나 거래 비용이 없다라든지, 상품을 무수히 잘게 자를 수 있다든지, 예를 들면 0.32개의 상품을 산다와 같은 가정은 우리도 당연히 받아 들일 것이다.


우리의 명시적 가정은 다음과 같다. 


첫째, 이 세상에 default (채무불이행 또는 부도) 는 없다. 즉, 게임에서 지더라도 게임 참여자는 자신이 지불해야 하는 돈이 있으면 손해를 보면서라도 그 금액을 갚는 세상을 가정할 것이다. 둘째, 게임 참여자는 돈을 벌 수 있는 기회가 있으면, 돈을 벌려고 노력할 것이다. 즉, 게임 참여자는 돈이 적은 것 보다는 돈이 많은 것을 선호한다. 


비록 여기에서 게임이라는 표현을 사용하였지만, 본 장의 논의 내용은 게임이론과는 전혀 관련이 없다. 여기에서의 게임이라는 표현은 추후에 상품이라는 표현으로 바뀔 것이다

```{tikz, echo=FALSE, fig.cap="The games", fig.align="center"}
\begin{tikzpicture}[]
\matrix[column sep=2mm, row sep=1mm] {
  & & & & & & & & & & & & & & & \\
  & &  \node {b}; &&&&& \node {22}; &&&&& \node {22};\\ 
  \node {a}; &&&&&\node {9};&&&&&\node {?};&&&&&\\
  & &  \node{d};&&&&& \node {22};&&&&& \node {22}; \\
  & \node{(1)};& & & & &\node{(1)}; & & & & &\node{(1)}; & & & &\\
};
\end{tikzpicture}
```


그림과 같은 동전 던지기 게임을 생각해 보자. (1)번 게임은 게임 참여자가
10만원을 베팅한 후 동전의 앞면이 나오면 (윗쪽) 11만원을, 동전의 뒷면이
나오면 (아랫쪽) 11만원을 받는 게임이다. 과연 이러한 것을 게임이라고 말할
수 있을까? 또는 이러한 상품이 현실에 존재할 수 있을까? 결론부터
이야기하면 `Yes''이다. 

이 상품을 생각하는 독자는 현재 10만원을 베팅하고 즉시 동전을 던진 후, 그 결과에 따라 즉시 11만원을 받는 경우를 생각하겠지만, 만약 베팅을 하는 시점과 동전 던지기 결과에 따른 payoff 사이에 시간이 3년인 경우를 가정하여 보자. 이러한 상품은 흔히 은행 예금, 또는 채권을 표현하는 것이다. 현재 시점에 10만원을 은행에 예금을 하면, 3년 후에 동전의 앞면이 나오나 뒷면이 나오나에 관계없이 무조건 11만원을 받는 것으로 이해할 수 있다. 또한 이 경우 동전의 앞면이 나올 확률이나 뒷면이 나올 확률은 아무런 역할을 못한다. 왜냐하면, 어떤 경우이던 무조건 11만원을 받기 때문이다. 우리는 default가 없는 세상을 가정하기 때문에 (1)번 상품은 이 세상에 존재하는 상품이 되는 것이다.


그러면 (1)번 게임에 베팅을 하는 게임참여자는 이해가 될 수 있지만, (1)번 게임의 딜러(베팅하는 돈을 받고, 게임의 상대방 역할을 해주는 사람)는 어떻게 이해할 수 있을까? 10만원을 받은 후 3년 후에 반드시 11만원을 돌려주어야 하는 역할은 은행의 입장에서 생각하면 쉽게 답을 얻을 수 있다. 10만원의 예금을 받고, 3년 간 대출을 해주고 1만원 이상의 이자를 받을 수 있다면 원리금의 합계가 11만원 이상이므로 충분히 해 볼만한 가치가 있다.  


다음으로 생각해 볼 게임은 (2)번 게임이다. 동전 앞면이 나왔을 경우 22만원, 뒷면이 나왔을 경우 아무것도 주지 않는다면 얼마를 베팅하여야 하는가? 이러한 게임을 처음 접한 독자는 확률을 생각하지 않을 수 없다. 동전의 앞면이 나올 확률이 얼마인가에 따라서 베팅할  금액이 달라질 수 밖에 없기 때문이다. 물론 이런 게임을 보고는`나는 손해를 볼 수 있는 게임은 안해''라면서 포기하는 사람도 있을 것이다.


하지만, 논의의 전개를 위하여 (2)번 게임을 하는 사람이 있고, 문제의 단순화를 위하여 동전의 앞면이 나올 확률은 정확히 1/2라고 하자. 


통계학에는 기대값이라는 개념이 있다. 우리가 흔히 이야기하는 평균의 또
다른 이름이다. 이 게임의 기대값은 
$$\begin{equation}
\frac{1}{2} \cdot 22 + \frac{1}{2} \cdot 0 = 11
\end{equation}$$ 
이다. 따라서 (2)번 게임의 합리적 베팅금액은 11만원일까?


물론 11만원을 베팅하겠다고, 또는 베팅하는 것이 맞다고 생각하는 사람도 있을 것이다. 그러나 많은 사람은 이러한 게임에 있어서 기대값인 11만원 미만의 가격을 베팅하고 싶어하는 경향이 있다는 것이 경제학의 일반적인 생각이고, 이러한 현상을 위험회피적, 또는 risk-averse하다고 표현한다.


우리는 (2)번 상품의 가격이 기대값인 11만원이 아니라 9만원에 거래되고 있다고 가정할 것이다. 여기서 9만원은 계산상의 편의를 위해 가정된 금액이다. 본 장을 다 이해하고 나서는 9만원을 다른 가격으로 바꾸어도 우리의 논리 전개는 달라지지 않는다는 것을 알 수 있을 것이다. 


우리가 풀고자 하는 진짜 문제는 (1)번과 (2)번 같은 상품이 주어진 가격으로 세상에서 거래되고 있을 때 (3)번 상품의 가격은 얼마가 되어야만 하는가이다. 또는 다른 표현으로 (3)번 상품의 가격이 얼마이어야만 arbitrage가 발생하지 않는가라는 문제이다.

## Arbitrage \label{arbitrage}\index{arbitrage}

Arbitrage는 우리말로는 재정거래\index{재정거래}라고도 하는데, 이는
한자어 번역이어서 들었을 때 우리의 이해에 별 도움이 되지 않는다. 우리는
영어단어를 번역하지 않은 채 그냥 사용하겠다. Arbitrage는 두개 이상의
상품의 가격 차이를 이용해 아무런 위험을 지지 않은 채 이익을 얻는
것이라고 표현할 수 있다. 우리가 찾고자 하는 (3)번 상품의 가격은
arbitrage가 존재하지 않게 만드는 가격, 즉 no-arbitrage price를 찾고자
하는 것이다. \\ \\ 이제 게임의 규칙을 설명하도록 하겠다. 아침 9시가
되면, (1)번, (2)번, (3)번 상품의 거래가 시작된다. 아침 9시에 게임의
참여자들은 각자 최선을 다하여 각각의 상품을 몇 개를 살 것인가 (베팅을
하는 경우) 또는 몇 개를 팔 것인가 (딜러가 되는 경우)를 외치고, 사겠다는
갯수와 팔겠다는 갯수가 서로 같아지는 경우 거래가 성립된다. 이후 오후
3시가 되면, 이 시장을 감독하는 감독관이 나와서 확률이 1/2인 동전을
던진다. 동전의 앞면이 나오는 경우 3개의 상품 모두 앞면이 나온 경우의
payoff를, 뒷면이 나온 경우는 모두 뒷면이 나온 경우의 payoff를 이용하여
현금으로 정산한다.

### 가격이 너무 비싸서 arbitrage가 발생하는 경우

앞서 서술한 바와 같은 규칙이 적용되는 시장에서 (3)번 상품의 가격이
16만원이라고 가정하여 보자. 그러면, arbitrage를 이용하여 돈을 버는
방법은 다음과 같다. 우선 (3)번 상품 1개를 팔아 16만원을 받고, 그 돈을
이용하여 (1)번 상품 1개, (2)번 상품 0.5개를 산다. 이때 발생하는 비용은
$10 \times 1 + 9 \times 0.5 = 14.5$, 14만 5천원이 된다. 따라서 16만원을
받고 14만 5천을 지불했으므로, 일단 내 주머니에 1만 5천원이 들어오게
된다. 일단은 이익이 발생했다.

오후 3시가 되어, 감독관이 나와 던진 동전이 앞면인 경우를 생각해 보자.
(1)번 상품으로 부터 11만원을 받고, (2)번 상품으로 부터 22만원의 절반인
11만을 받아, 모두 22만원이 되지만, (3)번 상품을 한개 팔았으므로
상대방에게 22만원을 주고 나면, payoff는 0이 된다. \\ \\ 이번에는 동전이
뒷면이 나온 경우를 생각해 보자. (1)번 상품으로 부터 11만원을 받고, (2)번
상품으로 부터 0만원의 절반인 0만을 받아, 모두 11만원이 되지만, (3)번
상품을 한개 팔았으므로 상대방에게 11만원을 주고 나면, payoff는 역시 0이
된다.

따라서 나는 오전 9시에 1만 5천을 이익을 보고, 오후 3시에 동전의 앞면이
나오던 뒷면이 나오던 항상 payoff가 0이으로 결과적으로 이익을 본 것이다.
어떻게 해서 이런 일이 발생할 수 있는 것일까? 어떤 이유로 이러한
arbitrage가 가능해 진걸까? 답은 바로 세 번째 시장에서 거래되는 상품의
가격인 16만원이 너무 비싸기 때문이다. 그럼 이번엔 반대로 (3)상품의
가격을 14만원으로 한번 낮춰보자.

### 가격이 너무 낮아서 arbitrage가 발생하는 경우

위에서는 (3)번 상품을 16만원을 받고 한개 판 후, (1)과 (2)번 상품에
베팅하였으나, 이번에는 반대로 한다. 즉, 1), 2) 상품을 팔고, 여기서 생긴
돈으로 3)번 상품을 사는 것이다. 일단 1)시장을 열어서 한 단위를 팔아서
10만원만큼을 받고, 2)시장을 열어서 반 단위를 판 뒤 4.5만원을 받는다.
그리고 1), 2) 시장에서 생긴 14.5만원 중에서, 3) 시장에 14만원을
베팅한다. 그러면 이 경우에는 처음 시점에 내 호주머니에 0.5가 남게 된다.

동전을 던져서 앞면이 나오면, 나는 1), 2) 시장에 각각 11만원을 줘야하고,
3) 시장에서는 22만원을 받는다. 동전의 앞면이 나온 경우 받는 돈과 줄 돈은
정확히 일치 한다.

그런데 처음에 0.5만원이 있었으므로, 나는 이 세 시장에서 0.5만원 만큼을
벌게 된다.

동전을 던져서 뒷면이 나오면, 나는 1) 시장에서 11만원을 주고, 2)
시장에서는 아무 것도 안 주고, 3) 시장에서 11만원을 받는다. 이 경우에도
마찬가지로 받을 돈과 줄 돈은 정확히 일치한다.

그러므로 이 경우에도 역시 처음에 0.5만원은 그대로 나의 소유가 되는
것이다. 즉, 위의 두 가지 경우를 통해서 우리는 가격이 너무 높게
책정되어도 돈을 벌 수 있고, 반대로 가격이 너무 낮게 책정되어도 돈을 벌
수 있다는 사실을 알게 되었다. 이런 식으로 가격이 너무 높거나 낮게
잡힘으로서 위험 없이 돈을 버는 것을 Arbitrage가 발생한다고 한다. Cf.
위험을 가지고 투자를 하는 것을 Risk를 Take한다는 표현을 쓴다. 이 경우
위험 없이 라는 표현은 Risk를 Take 하지 않고 라는 표현으로 고쳐 쓸 수
있다.

그렇다면 위의 문제에서 3)시장에서 거래되는 금융 상품의 적정가는
무엇일까? 답부터 미리 말하자면 14.5만원이 된다. 이렇게 했을 경우
Arbitrage가 존재하지 않게 되고, 상품의 적정 가격이 되는 것이다.

## 균형 가격 만들기

그렇다면 이 균형가격은 어떻게 만들어야 하나? 위의 경우를 바탕으로 생각해
보면 동전의 앞면이 나올 경우와 뒷면이 나올 경우에 내가 받을 돈과 내가
줘야 될 돈이 일치해야 하고, 이것을 바탕으로 처음 시장에서 거래가 끝난
뒤에 내 호주머니에 남는 돈이 없어야 한다.

일단 첫 번째 조건부터 만족시켜보자. 즉, 앞면이 나올 경우 받을 돈과
뒷면이 나올 경우의 받을 돈이 같게 만들어 보자. 이것을 수식으로 표현해
보자면 1) 상품에 만큼을 투자해서 앞면(뒷면)이 나오면 받는 돈과 2) 상품에
만큼을 투자해서 앞면(뒷면)이 나오면 받는 돈이 3) 상품에 투자해서
앞면(뒷면)이 나오면 받는 돈과 동일해야 한다. 이 두 조건을 수식으로
표현하면,

앞면의 경우 : 뒷면의 경우 :

이 두 식을 연립해서 풀면 , 가 나오게 된다.

이제 두 번째 조건에 관심을 가져보자. 내 호주머니에 남는 돈이 없어야
하므로, 처음에 거래할 때 들어가는 비용과 나가는 비용이 같아야 한다.
위에서 해를 해석해보면, 1) 상품에 1단위를 투자해야 하고, 2) 상품에
0.5단위를 투자해야 한다. 이 때 들어간 금액이 3) 상품을 통해서 마련한
자금과 같아지면 내 호주머니에 남는 돈이 없어지게 된다. 3) 상품의 가격을
라 하고, 이를 식으로 표현하면 다음과 같다.

따라서 3) 상품의 가격은 14.5만원이 된다. 이렇게 해야 동전의 면에
관계없이 돈을 벌 수 있는 기회가 사라지게 된다.

지금까지 나온 용어를 정리하면 다음과 같다.

arbitrage : 아무런 위험을 감수하지 않고도 돈을 벌 수 있는 것 균형가격 :
arbitrage가 발생하지 않는 가격.

지금까지 우리는 3) 상품을 1), 2) 상품을 이용해서 "복제" 했다고 이야기 할
수 있다. 이렇게 pricing을 하는 방법을 가지고 "Pricing by
replication"이라고 한다. 한 상품의 Payoff를 여러 개의 상품의 Payoff로
쪼개서 표현할 수 있다면, 그 상품의 가격은 여러 상품의 가격의 합과 같다는
사실을 알 수 있다. 이것을 응용해서 Payoff가 복잡한 상품의 Pricing도
가능하다.

그런데 지금 예를 들은 상품들이 실제로 현실에 존재하는, 그리고 거래되는
상품들일까? 이에 대한 답은 "Yes" 이다. 즉, 이러한 상품들은 현실상에
존재하고 있으며 활발히 거래되고 있다. 우리가 앞서 본 예에서 동전의
앞면과 뒷면에 대한 이야기를 경기의 상황에 빗대어서 생각해 보자. 즉,
동전의 앞면이 나오는 상황을 "경기가 좋아진다", 반대로 뒷면이 나오는
상황을 "경기가 나빠진다" 와 연결시켜 보자.

그렇다면 1) 상품은 경기가 좋건 나쁘건, 경기에 관계없이 일정한 수익률을
보장해 주는 금융상품이다. 우리가 쉽게 떠올릴 수 있는 예로는 은행에
예금을 한다고 생각할 수 있다. 하지만 투자에서는 만기 시점에 일정한
금액을 주는 채권(Bond 혹은 Fixed Income)을 주로 분석하므로, 앞으로 이런
형태의 상품에 대해서는 채권이라고 보도록 하자.

3)  상품의 경우 14.5만원을 투자해서 경기가 좋아지면 22만원을 벌고
    나빠지면 11만원을 받아 돈을 잃는 것으로 표현되고 있다. 이런 상품을
    잘 생각해보면 주식(Stock)을 떠올릴 수 있다.

마지막으로, 2) 상품은 경기가 좋아지면 9만원을 투자하고 22만원을 벌게
되므로 원금의 2배 이상의 많은 돈을 벌지만, 반대로 경기가 나빠지면
원금조차 회수하지 못한다. 이러한 금융 상품이 바로 우리가 앞으로 배울
"옵션(Option)"이다.

위의 예를 가지고 현실 세계에 적용시켜 보자. 우리는 시장에서 채권과
주식의 가격을 관찰할 수 있다. 그렇다면 이 가격을 사용해서 옵션의 가격을
결정할 수 있다. 또한 그렇게 되어야 한다. 만약 옵션의 가격이 채권시장과
주식시장에서 형성되는 가격을 고려하지 않고 결정된다면 누군가는 이 세
시장에 적절히 참가하여 무위험으로 돈을 벌게 된다. 이러한 arbitrage의
기회를 없애려는 것이 pricing의 가장 기본적인 idea이다.

## State Price를 이용한 가격 결정

위에 주어진 예제를 그대로 활용해 보자.

1)  H 11만원 / T 11만원 betting 10만\
2)  H 22만원 / T 0만원 betting 9만
3)  H 22만원 / T 11만원 betting 14.5만원

그저 방법론적인 측면에서 state price를 구하는 것을 설명하면 다음과 같다.
H와 T를 각각 , 로 치환해 보자. 그 후에 가격을 알고 있는 1) 상품과 2)
상품을 연립해서 , 를 구한 뒤, 이 값을 3) 상품의 Payoff에 곱해주면 3)
상품의 가격이 나오게 된다.

위의 두 식을 풀면 , 가 된다. 이제, 이것을 3) 상품에 적용시켜 보자.

이제 다음의 상품에 대한 가격도 State Price를 통해서 구해보자.

4)  H 1만원 / T 0만원
5)  H 0만원 / T 1만원

이 상품들의 가격은 어떻게 구하면 되겠는가? 이 때도 역시 과 를 이용하면
된다. 따라서 4) 상품의 가격은 가 된다. 그리고, 5) 상품의 가격은 가 된다.

이렇게 가격을 구하는 방식을 State Price를 이용한 가격 결정이라고 한다.
그러면 과연 State Price라는 것은 무엇일까? 간략하게 설명하면, State
Price는 해당 State가 일어났을 경우 1을 주는 자산의 가격을 의미한다.
우리의 예제를 통해서 생각해본다면 은 경기가 좋아지는 경우에 1을 주는
자산의 가격이라고 볼 수 있다. 그렇다면 이 예제의 경우에는 경기가 좋은
경우와 경기가 나쁜 경우, 이렇게 2 가지 경우가 존재할 수 있을 것이고,
현재 투자한 것에 대한 시간에 대한 보상이 주어져야 할 것이다. 이것을
바탕으로 위의 식을 다른 방식으로 표현해 보자. 여기서 난데없이 시간
가치에 대한 보상이 주어진 것에 대해서 의아해 할 수 있다. 기본적으로
우리가 생각하고 있는 상품이 채권과 옵션, 그리고 주식이므로 이자율에 대한
고려가 선행적으로 포함되어 있다고 보면 된다. 지금 이 부분에서는 이해가
어려울이지 몰라도, 뒤에서 자세히 배울 예정이므로 이런 개념이 있을 수
있겠구나 생각하고 넘어가면 될 듯 하다.

## Risk Neutral Probability

이 식에서 의미가 있는 부분은 아래의 부분이다.

,

이 부분을 생각해보면 경기가 좋을 경우와 나쁠 경우, 이렇게 전체 경우의 수
중에서 해당 State에 있을 경우의 비율을 구하는 것인데, 이 값들은 항상
0부터 1사이의 값만 가지게 된다. 즉, "확률"로서의 성질을 가지고 있음을 알
수 있다. 이 것을 일반화시키면 다음과 같이 표현할 수 있다.

, 여기서 은 실현 가능한 총 State의 수

우리는 이러한 분수 확률들을 risk-neutral probability(위험 중립
확률)이라고 부른다.

[중요] 위 확률은 동전의 앞면/뒷면이 나올 확률을 이용한 것이 아니라, 다른
가격들을 이용한 상대 pricing으로 확률을 구한 것과 같다. 따라서 위의 식을
표현할 때 라고 표시한다. 앞으로 이러한 위험중립확률을 이용해서 Pricing
하는 것을 공부할 예정이므로, 이 단계에서 확실하게 숙지하길 바란다.

이제 이 시간 가치에 대한 보상 부분을 생각해 보자. 일단 이해를 돕기
우해서 다음과 같은 6) 상품을 생각해 보자.

6)  H 1만원 / T 1만원

이 상품의 가격을 State Price를 이용해서 구해보면 이 나올 것이다. 그런데,
이 상품의 의미를 잘 생각해 보자. 내가 현재 만큼을 이 상품 시장에
투자한다면, 경기에 상관없이 1을 받을 수 있는 것이다. 이 때 우리는 이러한
상품의 개념을 이용해서 discount factor (할인율) 이라고 부른다. 잘
생각해보면 1) 상품인 채권의 형태에서 할인율이 사용되는 것을 알 수 있다.
즉, 이 예제에서 분석의 대상이 되는 채권은 쿠폰의 지급이 없는
무이표채이다. 따라서 만기에 한 번 액면금액만큼 지급되는 할인채인 것이다.
한 가지 더 알 수 있는 사실은 만약 채권의 가치를 계산할 때, 할인율을 로
하지 않으면, 채권만 가지고도 Arbitrage가 가능하다.

## 왜 Risk-Neutral Probability 인가?

이 예제에서 만기에 받는 payoff 들은 모두 정해져 있는 것으로 바꿀 수
없다. 다른 상품들의 가격이 모두 정해져 있는 상태에서 3) 상품의 가격이
14.5 가 나오게 만드는 가 바로 arbitrage가 나오지 않게 하는 값이다.
그리고 우리가 살펴본 예제에서는 이 가 동전이 앞면과 뒷면이 나올 확률인
이 아닌, 의 형태였다.

여기서 우리가 서두에 했던 이야기와 접목시켜 보자. 사람들은 위험에 대해서
서로 다른 성향을 보인다는 사실을 익히 알고 있다. 이렇게 risk에 대한
성향이 다른 여러 사람들이 같은 시장에 동시에 존재함에도 불구하고, 3)
상품의 가격은 무조건 14.5만원이어야 한다. 왜냐하면 14.5만원만이
arbitrage가 발생하지 않는 가격이기 때문이다. 즉, 시장에서 결정되는
가격은 사람들이 시장에 대해서 느끼는 효용과 관계없이 결정된다.

위에서 우리가 구한 확률은 arbitrage가 발생하지 않는 균형가격을 만드는
확률이다. 이것이 risk에 대해서 중립적인 성향을 가지는 사람이 미래를
바라보고 행동하는 확률과 같기 때문에 그 값을 risk-neutral
probability라고 부르는 것이다.

Cf. 여기서 주의할 점이 있다. Risk를 좋아하는 사람이라고 하더라도
Arbitrage 기회를 싫어하는 것은 아니라는 점이다. Risk에 대해서 어떤
성향을 가지고 있던지, Arbitrage 기회가 있으면 이것을 이용하려고 한다.
그러므로 수요와 공급의 논리에서 본다면 Arbitrage가 가능한 상품에 대한
수요가 급격히 증가하게 되고, 공급은 한정되어 있거나 한시적으로 줄게 되어
자연히 해당 금융 상품의 가격이 상승하게 되고, Arbitrage의 기회는 곧
사라지게 된다.
