# 이항 옵션 가격 결정 모형 \label{section-CRR}

\subsection{One step 모형}

저자의 이름을 따서 CRR이라고 부른다. 이전에 Black Scholes 라는 방정식을 어려운 방식을 통해서 유도했었는데, 이 논문의 Contribution은 앞에서 알아본 Binomial Tree를 이용해서, 간단한 수학만 가지고 No Arbitrage Condition을 만족하는 포트폴리오에 극한을 취하면 Black Scholes 방정식으로 유도할 수 있다는 것이다. 

3Page의 The Basic Idea를 보자. 여기에 현재 50인 기초 자산이 있는데, 만기에 이 자산의 가격은 25가 될 수도 있고, 100이 될 수도 있다. 이 때 25%의 이자율로 돈을 빌릴 수 있다고 해보자. 이런 상황에서 행사가격이 50인 Call Option의 가치만 정해지지 않았다고 해보자. 이 때 논문에서 제공하는 대로 한 번 해보자. 

(1) Call option을 3개 팜
(2) 50짜리 주식을 2개 삼.
(3) 40을 25%의 이자율로 대출받음.

이런 상황에서 No Arbitrage Condition을 만족시키기 위해서는 현재 가치가 이 Portfolio의 가치가 0이 되어야 하므로, 다음의 식이 만족해야 한다. 




그러므로 이 때의 Call Option의 가격은 20이 되어야 한다. Table 1을 보면 만기시의 Payoff가 정확히 ‘0’으로 일치하기 때문에 No Arbitrage Condition도 만족한다는 사실을 알 수 있다. 미래의 portfolio의 가치가 항상 0이기 때문에 현재 시점의 가치도 0이 된다. (arbitrage가 존재하지 않는다고 가정했을 때) 즉 이걸 만족해야 하기 때문에 Call Option의 가격은 20이 되어야 한다. 그리고 논문에 보면 친절히 왜 Call Option의 가격이 20이 아니면 안되는지에 대해서 잘 나와 있다. 이건 학기 초에 예제를 통해서 충분히 설명하였으므로 이 부분은 넘어가도록 하겠다. 

이제 4page의 3번을 보자. 이 부분은 앞에서 본 예제를 일반화한 것에 지나지 않는다. 즉, 앞에서는 Call Option의 개수와 몇 개의 주식을 살 건지, 그리고 얼마를 빌릴 건지 다 정한 상태였지만, 여기서는 그게 정해져 있지 않은 상태에서 No Arbitrage Condition을 이용해서 우리가 구해보는 것이다. 이 그림은 이미 익숙할 것으로 생각한다. 여기서 주의해야 할 점은 r이라고 하는 것은 이 논문에서 gross rate, 즉 [1+이자율]이 된다. 

Portfolio를 만든다고 해보자. 위의 예제에서 알아본 바와 같이 만기 시에 어떤 State가 발생하던지 해당 Portfolio의 가치를 정확히 Call Option의 가치와 같게 만드는 Portfolio를 만들어 낼 수 있다면, 지금 시점에 Call Option 하나에 대해서 얼마나 받아야 될지 구할 수 있다. 즉, Call Option의 균형 가격을 구할 수 있다. 

Stock을 Δ만큼 사고, B만큼의 무위험 채권 포트폴리오를 구성했다고 할 경우 만기시 State 별로 그 포트폴리오의 가치는 아래와 같다. 

, 

그런데 이 값이 각 State별 Call Option의 가치와 같아야 한다. 그러므로 다음의 두 식이 성립하게 되고, 이 식을 바탕으로 과 에 대해서 구할 수 있다.

,  

,  

이 상태에서 No Arbitrage Condition을 생각해 본다면, 현재 Call Option의 가격은 현재 Portfolio를 구성하는데 들어가는 비용과 같아야 한다. 그러므로 다음의 식이 성립한다. 



이 걸 바탕으로 위에서 구한 과 를 집어넣으면, 논문에서와 같은 식이 나오게 되는 것이다. 논문에도 등장하고 있지만, 여기서 유의해야 할 성질들은 다음과 같다. 첫 째로, q라고 하는 숫자 자체는 formula에 나타나지 않는다. 투자자가 만기 시점에 각 State가 어떤 확률로 일어날지, 즉 미래에 대해서 어떠한 생각을 가지고 있는지에 관계없이 우리가 를 결정할 수 있다는 것이다. 

여기서 를 결정할 때 영향을 주는 요인은 기초자산의 움직임 밖에 없다. 그러므로, Call Option 가치를 계산할 때, 불확정적으로 영향을 주는 것은 기초자산 하나 밖에 없다. 그리고, 앞에서 충분히 설명하긴 했지만 중요하니깐 다시 한 번 살펴보자. q는 실제 어떤 일이 일어날 확률이다. 그런데 p라는 확률은 risk neutral한 사람이 세상을 바라볼 확률과 같아진다. 이것에 대한 이야기는 앞에서 충분히 했으므로 앞의 Appendix들을 참고하길 바란다. 

이제 2-step으로 나간 경우이다. 이제는 그림만 보아도 어떻게 해야하는 건지 다 알 수 있을 것이다. 기초자산의 가치가 움직이고, 이 것의 만기시 Payoff가 결정되고 이것을 할인하는 과정을 거치는 것. 그리고 이것이 No arbitrage Condition을 만족해야 하는 것, 이게 우리가 해야할 과정의 전부이다. 

이런 과정을 여러번 한다고 생각해보자. 즉, n-step에 대해서 generalize 시키면 다음과 같이 표현할 수 있다. (Call Option의 경우)



여기서 라는 숫자를 설정해보자. 즉, 동전의 앞면이 몇 번 나와야만 max 안에 있는 값이 0보다는 큰 숫자가 나올 것인가? 이를 만족시키기 위해서 최소한 상승해야 하는 횟수가 바로 이다. 이 식을 대해서 놓고 a에 대해서 구하면, 다음의 식이 된다. 



따라서 가 이거보다 큰 정수가 되면 max안의 부분을 아래와 같이 바꿀 수 있다. 즉, 이 때 j=(a~n) 까지만 합하면 된다.



이제 논문으로 돌아가면 와 이 나오고 있는데, 이건 곧 binomial 분포에서 확률을 바탕으로 한다는 것이다. 그런데, Binomial Distribution에서 는 이상의 부분을 다 합한 거라고 보면 된다. 즉, 경계값을 바탕으로 오른쪽 부분을 다 합한 거라고 보면 된다. 

이제 11page 아래의 식을 보자. 와 가 있는데, 이 값들은 State Price라고 보면 된다. 앞에서 우리가 State Price에 대해서 잘 알아보았으니깐, 무슨 의미인지 잘 알거라 생각한다. 즉, 할인율과 그 State가 일어날 확률을 곱한 것과 같다. 이 것을 식으로 표현한 것이 바로 논문의 다음 식이다. 

,  

4장은 예제를 들어서 설명한 것이니깐 앞의 예제들을 이해했다면 충분히 잘 할 수 있을 거라 생각한다. 

그런데, 이런 의문이 들 수 있다. 지금 Discrete하게 보아서, 하루가 지나면 S = uS | dS 가 되어 버린다고 보고 있는데, 보통 주가 변동은 이것보다 훨씬 더 많은 값을 가지게 된다. 또한 하루에 한 번 밖에 trading을 못한다고 가정하였는데, 실제로 우리는 거의 매시에 trading 할 수 있다. 만약 매 분마다 거래가 가능하다고 본다면, 9시부터 3시까지니깐 총 6시간이어서 하루 동안에는 총 360 step이 있을 수 있다. 즉, 지금 10만원 하는 주식이 오늘 하루가 지나면 361개의 다른 값을 가지도록 모델링이 가능한 것이다. 보통 소수점 이하 2번째 까지 쓰는데, 더욱 더 잘게 자르면 소수점 이하 3번째 값까지도 가질 수 있다.

그런데 주가 변동을 이렇게 분할로 계산할 경우, 일할 때 쓰는 나 를 그래도 사용하면 너무나 값이 이상하게 커지게 된다. 왜냐하면, 일할 때 쓰는 가 1.1이라고 했을 때, 이 값을 분할로 바꾼 경우에도 그대로 쓴다면 하루가 지난 뒤에 최대로 가질 수 있는 값은 이 아닌 이 되게 된다. 즉, 지금 10만원하는 주식이 하루가 지나면, 3540만원이 될 수도 있다는 것이다. 그러므로, 일할이 아닌 시할, 혹은 분할 계산할 경우 시간 간격에 따라 이를 조정해 줄 필요가 있다. 

전체 시간을 개로 자르면 각각의 거리는 가 된다. 이 것을 식으로 표현하면 다음과 같다. 



는 한 스텝의 시간이기 때문에 trade가 점점 더 자주 일어나면 일어날수록 0에 가까워질 것이다. 앞에서 보았듯이 나 는 조정해 주어야 한다는데, 모두 동의를 했을 것이다. 그런데 마찬가지 이유로 도 역시 조정해 주어야 한다. 

여기서부터 이제 Binomial과 Continuous가 헷갈리기 시작하므로, 이 부분을 읽을 때는 차이점을 잘 숙지하고 읽어야 한다. 첫 번째로 등장하는 Notation이 이다. 단위 시간당 이자율이 이라고 하였으므로, 시간 동안의 이자율을 다음과 같이 표현할 수 있다. 



그런데, 이 와는 별개로 이 시간을 스텝으로 나눈다고 생각해보고, 이 때 각 Step별로 적용되는 이자율을 이라고 표현해 보자. 그러면 다음의 식이 성립해야 한다. 



을 기준으로 한 것 - 구간별 이자율은 













를 기준으로 한 것 - 구간별 이자율은 



이 것을 보면 이 에 의존한다는 사실을 알 수 있고, 이 증가하면 이 감소하고, 이 감소하면 이 증가한다. 

그리고 를 만기시 기초자산의 가격이라고 생각해 보자. Binomial하에서 를 표현해 보면 다음과 같은 식으로 될 수 있다. 논문에서처럼 , , , , 라고 한다면 다음과 같이 된다. 



여기에 log를 취해보면 다음과 같이 표현할 수 있다. 



그런데, 이걸 일반화 시키면 다음과 같이 표현할 수 있다. 



여기서 확률 변수는 이므로, 이 값을 바탕으로 위의 를 취한 것의 기댓값과 분산을 구해보면 다음과 같다. 여기서 Binomial의 기댓값과 분산을 구하는 식을 구하면 다음과 같이 된다. 





이 상태에서 을 무한대로 보낸다면, 현실과 비슷하게 만들 수 있다는 생각을 할 수 있다. 이제 위의 식에서 을 무한대로 보냈을 때, 각 값의 limiting 값이 다음으로 수렴하게 만드는 , , 그리고 를 한 번 정해보자. 

,  

사실 이런 조건을 만족시키는 , , 그리고 는 여러 종류가 있다. 하지만, 여기서는 논문에 나온 것만 고려하기로 하자. 

,    ,  

이제 이 값을 넣어서 을 무한대로 보냈을 때 수렴하는지 체크해보자.







그러므로 증명을 다 했다. 여기서  로 놓고 한 번 시도해 보자. 



정리하면 다음과 같다. 



두 번째 식을 정리하면 다음과 같다. 





이제 와 의 계수를 구해보자. 

,  

,  

잠시 여정을 떠나기에 앞서 우리의 목적을 다시 한 번 점검해 보자. 이 논문의 목표는 을 무한대로 보냈을 때, Binomial Tree로 Pricing을 한 것이 Black Scholes Equation으로 간다는 것이다. 

->  

여기서 사용되는 것은 Central Limit Theorem인데, 즉, Binomial Distribution이 Normal Distribution으로 간다는 것을 보여야 한다.  Converge in Distribution
그런데 20page에서 맨 마지막에 한 조건이 성립을 해야 우리가 하려는 이야기를 할 수 있다는 사실을 보여주고 있다. 그 조건이 바로 Unbiased Condition이라고 하는데, 값이 0으로 가야된다는 것을 의미한다. 



여기에 위에서 구한 각 값을 넣고 구했을 때, 위의 식이 성립해야 한다. 



이 때  이므로, 이 값을 대입하고 구해보자. 





그러므로 을 무한대로 보내는 경우 0으로 가게 되어 Initial Condition이 성립하게 된다.  사실 대입을 하지 않아도 의 극한값이 상수이기 때문에 이 분자에 있어서 0으로 감을 쉽게 생각할 수 있다. 


이제  measure 하에서의 값들을  measure로 표현해보자. 이건 극한을 취하면 된다. 즉, 다음의 식을 유도하는 것이다. 



이 것을 유도한다는 것은 다음이 성립함을 보이면 된다는 것과 똑같은 의미이다. 



그런데, 의 경우는 윗부분, 즉 높이 올라갈 경우를 상정해서 고려하고 있지만, 의 경우에는 부터 특정 값까지의 확률을 구하는 것이므로, 총 확률을 합한 값이 1이 된다는 사실에 착안해서 다음의 식을 유도해 보자. 


는 Binomial에서 up의 횟수

여기서 아직은  measure 하에서의 세상이므로, support가 정수이고, 작은 범위를 하나를 뺀 것보다 작거나 같은 것으로 고칠 수 있다. 이걸 표준화하면 다음과 같이 고칠 수 있다.



여기서  ,  , 
임을 이용해서 전개를 하면 다음과 같이 된다. 

,    ,  

그런데 우리가 관심 있는 범위는 마지막에 기초 자산의 가격이 행사가격보다 큰 범위이다. 이것을 Binomial의 형태로 표현하면 다음의 식과 같다. 



이것을 바탕으로 의 범위를 구할 수 있다. 



이 값을 만족시키는 최소한의 값을 라고 표현하자. 그런데, 위에서 보다 작다는 표현을 보다 같거나 작다 라는 표현으로 고칠 수 있었으므로, 이것을 무한 번 쪼갠다면 1을 빼는 것이 아니라 아주 조금만 빼도 될 것이다. 이것이 바로 continuous version에 대한 직관적인 이해라고 볼 수 있다. 이 것을 식으로 표현한 것이 바로 다음의 식이다.



이 것을 위의 식에 그대로 대입하면 다음의 식이 나온다. 



이제 중심극한정리를 이용하는 핵심적인 부분만 남았다. 



이 가 로 수렴하는 것을 보이면 된다. 다른 말로 Discrete Version을 Continuous Version으로 바꾼다는 의미와 동일하다. 이렇게 하기 위해서 각각에 대해서 taylor Expansion을 해보자. 



이제 로 치환해 놓고 , , 그리고 를 전개해 보자. 2nd Order까지 전개 해보자.  여기서 을 전개할 때에는 이 공식을 이용해서 전개한다. 








이를 에 대입하고 을 무한대로 보내서 전개해 보자. 



성립함을 보였으니, 이제 을 무한대로 보내보자.





정규분포의 대칭성을 이용해서 정리하면.




이제  Version의 경우도 알아보자. 



이전과 같이 Taylor 전개를 하되, , 를 2nd Order까지 전개 해보자. 





이를 에 대입하고 을 무한대로 보내서 전개해 보자. 



성립함을 보였으니, 이제 을 무한대로 보내보자.





정규분포의 대칭성을 이용해서 정리하면.



지금까지 있었던 일들을 쭉 정리해 보자. 일단 Binomial Tree에서 No Arbitrage Condition을 이용해서 One Step Binomial Tree를 이용해서 Call Option의 가격을 구할 수 있다는 사실을 알았다. 그리고 이것은 스텝의 수가 1개인 경우뿐만 아니라 스텝의 수가 인 일반적인 경우로 확장을 시켜도 성립한다는 사실을 알게 되었다. 그리고 이 때 사용되는 확률은 현실에서 일어나는 가 전혀 등장하지 않는 라는 사실을 알게 되었고, 이 가 위험중립확률이라고 불린다는 사실도 알았다. 그리고 우리는 이 스텝인 을 무한대로 보내서 계산한다면 Binomial Distribution이 Normal Distribution으로 바뀌면서 Black Scholes Equation으로 바뀌게 된다는 사실을 알게 되었다. 그리고 , , 그리고 를 각각 Taylor 전개해서 근사화하면 Continuous Version으로 바꿀 수 있다는 사실도 알게 되었다. 
