# (PART) Financial Mathematics {-}
# Browian Motion

Random Variable

동전 던지기를 무한히 한다고 가정해 보자. 이 결과를 기록한다면 동전의 앞면, 뒷면 이런  식으로 쭉 적어나갈 수 있을 것이다. 이 때 동전의 앞면을 1, 뒷면을 0 으로 바꿔 적는다면, 10111001 이런 식으로 적을 수 있을 텐데, 이 이야기는 곧 0과 1 사이의 한 숫자를 뽑는 것과 같다는 것을 알 수 있다. 

갑자기 동전던지기를 무한히 해보라고 하더니 이게 0과 1사이의 값을 뽑는 것과 같다고 말하니깐 속는 것처럼 느낌이 들 수도 있다. 하지만 이진법을 생각해 보면 이해하기 쉽다. 아까의 예를 이진법의 형태로 이렇게 한번 적어보자. 

0.10111001…(2) 

우리가 고등학교 시절에 배운 방법을 이용하면 이걸 10진수로 바꿀 수 있다. 그러면 결국 0과 1사이의 값으로 바꿀 수 있다는 사실을 알 수 있다. 예를 들어 다음의 이진수를 10진수로 바꾸어 보자. 

0.011111111…(2)  

과연 얼마일까? 1/2이다.  
즉, 0, 1 사이에서 수를 뽑았는데 그 값이 일 확률은 동전을 무한 번 던졌을 때, 처음에 뒷면이 나오고, 나머지는 계속해서 앞면이 나오는 0.01111…(2) 시퀀스가 나오는 확률과 같다는 의미이다.

따라서 동전을 무한히 던진다고 하는 것은 매우 특이한 것이다. 무한히 동전을 던진 결과 다음과 같은 시쿼스로 나온다고 생각해 보자. 






"A random variable is a real-valued function defined on the sample space."
Random Variable은 Sample space에 대해서 정의된 실수 값을 갖는 함수이다. 


위에 (omega)라고 적은 이유는 무엇인가? 위의 정의에서 알 수 있듯이 Random variable은 변수가 아니라 함수이기 때문이다. 즉, "sample space"에서 어떤 하나의 숫자를 만들어내는 함수이다. 그리고 이 경우 이 함수가 가질 수 있는 값은 1 또은 -1 이라는 의미이다.


Random walk process






이렇게 표현되는 것을 랜덤 워크라고 한다. 위의 식을 다른 형태로 표현해 보면 다음과 같다. 



즉, 이전기 자신 값에 새로운 충격을 계속 더해 나간 것이라고 이해할 수 있다. 그래프로 그려보면 아래와 같이 나온다. 1, -1 이 랜덤으로 나오는 것을 무한히 더했다고 해 보면 쉽다.



Cf. Martingale 


,  ,  , 

이 각각의 확률변수들이 independent 하다. 즉, 각 부분의 증분이 앞뒤와 관련이 없다. 


의 통계적 성질
이제 의 통계량에 대해서 더욱 깊게 알아보자. 가장 기본적으로 생각할 수 있는 것이 1, 2차 모멘트 이므로, 평균과 분산에 대해서 알아보자. 일단 평균을 먼저 구해보자. 



즉, 각각의 경우에 대해서 독립이므로 합의 기댓값은 각각의 기댓값의 합으로 바꿀 수 있고, 각각의 기댓값은 0 이므로, 결국 기댓값은 0 이다. 

이제 분산을 구해보자. 만약 일반적인 경우라면 분산은 다음과 같이 표현될 수 있다. 



이 경우 각각이 독립이므로 분산을 구할 경우에 공분산 부분을 고려하지 않아도 되므로 위의 경우처럼 구할 수 있다. 

이제 이 값 자체보다 증분에 대해서 공부해 보기로 하자. 



(이 때 인덱스를 조심하도록 한다. 1~90 에서 1~80을 뺐으니 81~90 이 되는 것임을 명심한다.)

다음의 예를 생각해 보자. 

, 





이제 이보다 좀 더 복잡한 Random Walk을 생각해보자. (사실은 이것이 Scaled Random Walk 으로 볼 수 있다.)

,  

일 때,

의 통계량에 대해서 알아보도록 하자. 일단 이것의 기댓값부터 구해보면 0이라는 사실을 알 수 있다. 아직 의 의미가 잘 안 와서 이것의 기댓값이 0이 된다는 사실을 이해하지 못할 수 있는데, 조금 더 보충설명을 하면 다음과 같다. 이것은 여전히 기본적으로 동전 던지기와 같다. Binomial Tree를 그릴 때 동전의 앞면이 나오면 위로, 뒷면이 나오면 아래로 내려가게 그린다. 앞면이 2번 나오면 그 값이 2가 되고, 뒷면이 2번 나오면 그 값이 -2가 되는 것을 식으로 나타내면 바로 가 되는 것이다. 그런데 이 것의 스케일을 에서 으로 조금 조정한 것이 위의  함수이다. 의 스케일은 1이고 의 스케일은 이다. 이 때의 스케일은 동전의 앞면이나 뒷면이 나왔을 때, Y축을 기준으로 했을 때 얼마나 아래 위로 움직이는지를 나타내는 것이다. 
여기서 은 정해진 상수이므로, 기댓값을 구할 때 곱해주기만 하면 된다. 앞에서 증분의 기댓값이 0이라고 하였으므로 위의 증분의 기댓값도 0이 된다. 

그렇다면 이 상태에서 n이 무한대로 가면 어떻게 될 것인가? 즉, 동전 던지기를 무한히 많이 하는 경우에도 위의 식에 대한 우리가 알고 있는 통계적인 성질들이 그대로 유지될까? 일단 아래와 같이 극한을 취해보자. 



우리가 앞에서 본 바와 같이 이항분포는 극한을 취하면 정규분포로 가게 된다. 여기서 을 증가시킨다는 의미는 결국 이 값을 정규분포로 보내겠다는 의미이고, 이것이 바로 그 유명한 중심 극한 정리이다. 

그렇다면 정규분포로 간다는 의미는 무엇일까? 를 고정시킨 상태에서 Binomial Tree의 마지막 노드에 해당되는 값들이 오른쪽에 막 찍힐 것이다. 여기서 을 늘린다는 의미는 이 값들의 차이를 아주 잘게 자른다는 의미이다. 기간을 1기간이라고 하면 Binomial Tree의 Node는 위 아래 2개이고, 오른쪽의 값도 2개가 된다. 기간을 2기간으로 쪼개면 노드는 총 6개가 되고, 오른쪽의 값은 3개가 된다. 기간을 3기간으로 쪼개면 노드는 총 12개가 되고 오른쪽의 값은 4개가 된다. 즉, 기간이 증가할수록 오른쪽의 값도 증가하며, 그 값은 기간에 1을 더한 값이 된다. 
그리고 우리가 구상한 함수의 형태에 따르면 상하의 움직임의 폭이 이 되므로 마지막에 가질 수 있는 값의 범위는 크게 변하지 않을 것이다. 이 때 마지막에 찍히는 점들의 빈도수를 그려보면 정규 분포에 근사가 가능한 분포가 나온다는 의미인 것이다. 이를 중심 극한의 정리라고 한다. 

여하튼 결론은 을 무한대로 하면 함수를 정규 분포로 근사할 수 있다는 것이다.


중심 극한 정리 증명

이 과목은 금융공학이다. 그러므로 말로만 하고 지나갈 수는 없다. 수식을 통해서 증명해 보자. 

Moment generating function(MGF)

이는 Moment를 만들어 주는 함수이다. 통계학에서 Moment는 , , , ... 이 각각을 Moment라고 부른다. 각각을 1차, 2차, 3차 모멘트라고 하는데, 이걸 직접 계산하는 게 의외로 어렵다. 그래서 대부분 Moment Generating Function이라고 하는 다른 종류의 함수를 이용하게 된다.



이걸 구할 수 있으면 Moment Generating Function이 되는 것이다. 함수 를 에서 Taylor전개하면 다음과 같다. 



따라서 에 대해서 미분해서 다음의 식을 얻을 수 있다. 



만일 적률모함수를 구할 수 있다면, 적률모함수를 사용해서 적률을 구하는 것이 편리하다. 다음은 정규분포의 적률모함수이다. 



이렇게 이 식을 알고 나면 정규 분포의 Moment는 다 구할 수 있게 된다. 어떻게 구하나? 이를 에 대해서 한 번 미분하고 에 0을 대입하면, 1차 moment를 구할 수 있고, 2번 미분하고 에 0을 대입하면, 2차 moment를 구할 수 있다. 즉, 차 moment를 구하려면 MGF를 번 미분하고, 0을 대입하면 된다.



이렇게 한 다음에 을 넣으면 가 나오게 된다.

이제 우리가 정규분포의 MGF를 알았으므로, 우리가 가지고 있는 분포의 극한값이 위의 정규분포의 MGF로 수렴한다면 이 정규 분포로 감을 증명할 수 있다. 



여기에서의 는 일반적인 MGF 식의 와 같은 의미이다. 우리가 이미 를 변수로 썼기 때문에 다른 걸로 한 것이지 별다른 의미는 없다. 



여기서 합을 곱으로 바꿔준 것은 각각이 independent 하기 때문에 합의 곱으로 바꿀 수 있고, 이 곱을 기댓값 밖으로 밸 수 있으므로 위와 같은 식이 성립할 수 있는 것이다. 이제 여기에 극한을 취하면 되는데, 곧바로 극한을 취하면 괴로우므로 우선 ln을 취한 다음에 극한을 취해보자. 양변에 ln을 취하면



여기서 를 아래와 같이 치환해 주자. 





이제 이 것의 극한값을 취해보자. 



그런데 위의 값들에 을 대입하면 안 구해진다. 따라서 로피탈의 정리를 이용하여 구해야 한다.



여기서 갑작스럽게 분모의 반을 계산과정에서 제외한 것은, 극한값이 1이니깐 계산 결과에 영향을 안 주기 때문이다. 그렇게 한 후에 아래 위에 로피탈을 취해주면 다음과 같이 된다.



이제 이를 원래 모양으로 다시 돌려주기 위해서 exp를 취해준다.



이를 정규분포의 MGF와 비교해 보면 이것의 분포가 정규분포이면서 평균은 0이고 분산은 라는 것을 알 수 있다. 이것을 이렇게 표시할 수 있다. 



이제 증명을 완료했다. 을 무한대로 보내면 이 정규분포로 감을 알 수 있다. 이러한 증명 과정을 보여주는 목적은, 이 너무 크지 않은 상태에서 어떤 모습일까를 생각해 보게 하기 위해서이다. 예를 들어 동전 10번 던지기를 가지고 H=1/√10, T=-1/√10라고 해 보자. 이걸 가지고 머리로 생각해 본 상태에서 n=10이 아니라 n을 매우 크게 만들면 동전이 누적되는 모습이 어떻게 될까를 짐작해 보자는 것이다. 그 최종 결과들을 보면 결국 표준 정규분포가 나온다는 것이 지금까지 증명한 내용이다.


KCT ) 일단 이 부분의 수업을 제대로 이해하기 위해서는 random variable이 무엇인지 알아야 한다. 그러나, 필자의 경험을 비추어 봤을 때, 수리통계학을 듣지 않은 상태에서 금융공학의 이해(1)을 들은 학생도 꽤 있을 것으로 보인다. 사실 필자도 통계학입문만 들은 상태에서 들어서 참 많이 어려워했던 기억을 가지고 있다. 필자와 비슷한 상황에 처해있는 학생들을 위해서 아주 간략하게 random variable 에 대해서 언급하고자 한다. 

위에서 사용한 동전 던지기 문제를 생각해 보자. Fair coin(앞면과 뒷면이 나올 확률이 같은 동전)을 2개를 던진다고 해보자. 이 때 나올 수 있는 결론의 가능성은 다음의 4가지 경우이다. 

{ 앞면,앞면 },{ 앞면,뒷면 },{ 뒷면,앞면 },{ 뒷면,뒷면 }

이 때 우리가 이것을 가지고 내기를 했다고 해보자. 예를 들어 앞면이 나오는 횟수에 만원을 곱한 만큼 받고, 뒷면이 나오면 아무 것도 안 줘도 된다고 하자. 매우 불공평한 게임이다. ^^;;

어쨌든 이 경우 우리가 관심 있는 건, 앞면이 나오는 동전의 횟수다. 위의 경우를 본다면 순서대로 다음과 같이 표현할 수 있다. 

( 2 , 1 , 1 , 0 )

여기까지 이해가 갔으면 확률 변수에 대해서는 다 이해한 것이다. 즉, sample space 에 있는 원소들을 real value 와 연결해 주는 함수가 바로 확률 변수이다. 여기서 sample space의 원소는 앞면과 뒷면을 조합한 위의 4가지 경우이고, real value 들은 0, 1, 2 이렇게 3가지이다. 그렇다면 확률변수는 바로 “앞면이 나온 횟수“ 인 것이다. 

이대로 끝내기 좀 아쉬우니 다른 걸 해보자. 이제 게임을 조금 공평하게 해서 앞면이 나오는 횟수에 만원을 곱해서 내가 돈을 받고, 뒷면이 나오는 횟수에 만원을 곱해서 돈을 준다고 하자. 그러면 우리는 이제 앞면이 나오는 횟수 뿐만 아니라 뒷면이 나오는 횟수에 대해서도 관심이 생기게 된다. 

위의 예를 그대로 쓴다면 앞면이 나오는 경우는 다음과 같이 표현되고, 

( 2 , 1 , 1 , 0 )

뒷면이 나오는 경우는 다음과 같이 표현된다.

( 0 , 1 , 1 , 2 )

여기서 각 숫자가 나올 확률을 구해보자. 즉, P ( 2 ) , P ( 1 ) , P ( 0 ) 를 구해보자. 

앞면이 나오는 경우에 관심이 있는 경우의 확률은 각각 다음과 같다. 

{ P ( 0 ) , P ( 1 ) , P ( 2 ) } = { 1/4 , 1/2 , 1/4 }

마찬가지로 뒷면이 나오는 경우에 대해서도 구해보면 다음과 같다. 

{ P ( 0 ) , P ( 1 ) , P ( 2 ) } = { 1/4 , 1/2 , 1/4 }

여기서 재미난 사실을 하나 알 수 있다. 

{ 앞면,앞면 },{ 앞면,뒷면 },{ 뒷면,앞면 },{ 뒷면,뒷면 }

위의 조합에 대해서 확률을 구하면 앞면이 나온 횟수로 할 때나 뒷면이 나온 횟수로 할 때 각각 확률이 같다는 것을 알 수 있다. 즉, 앞면이 2번 나온 경우는 뒷면이 안 나온 경우와 같고, 앞면이 1번 나온 경우는 뒷면이 1번 나온 경우와 같으며, 앞면이 안 나온 경우는 뒷면이 2번 나온 경우와 같다. 이러한 관계에 있는 함수를 identically distributed 하다고 한다. 보통 통계학 관련 책을 읽다보면 iid 라는 말이 많이 나오는데, 뒤의 id 부분이 이 의미이다. 

조금 더 갈려다가 절제한다. 그러나 조금 더 가고 싶은 사람들은 확률변수 : “앞면이 나온 횟수” 와 확률변수 : “처음에 앞면이 나온 조합” 으로 바꾸어서 비교해 보면 identical의 의미를 더욱 깊게 알 수 있을 것이다. 

\subsection{Stochastic differential equations}
Stochastic differential equation (확률 미분 방정식)

일반적으로 미분방정식은 다음과 같은 형태로 표현된다. 



이 미분방정식을 다음과 같은 형태로 바꿀 수 있다. 



그럼 원래의  함수는 

, 여기서 C는 상수.

이와 같다. 이런 것을 미분방정식을 푼다라고 말한다.

그런데 이 라고 하는 것은 deterministic form 이다. 따라서 이게 확률적인 것이라면 추가적인 term이 더 있어야 한다. 그래서 뒤에 라고 하는 것을 덧붙인 것이다. 이 가 어떤 값이냐에 따라서 그 형태가 변하게 된다.



주가를 예를 들어 설명해보자. 앞쪽의 것은 deterministic 하다는 것이다. 그런데 주가가 그런가? 아니다. 변동성이 있다. 그것을 설명하는 것이 바로 뒤쪽의 Volatility란 것이다.

그럼 이제 우리가 수익율을 계산한다고 하여 보자. 를  시점에 내가 가지고 있는 금액이라고 하자. 이를 은행에 맡겼을 경우, 은행에 이자가 붙게 된다. 이를 수식으로 표현하면 아래와 같게 표현할 수 있을 것이다.



이 식의 마지막은 을 무한으로 했을 때 성립한다. 

그리고 의 증가량은 아래와 같다.



위와 같이 나오게 된다. (뒤쪽은 delta를 아주 작게 했을 때)  Exponential을 Power Series를 이용해서 타나낼 수 있는데, 여기서 의 값이 충분히 작으면 Power Series의 2차항 이하는 무시할 수 있다. 그렇기 때문에 저런 근사식이 가능한 것이다. 



그런데 이럴 리는 없다. 주식의 가격은 올라갈 수도 있고 내려갈 수도 있다. 그래서 만으로 표현하는 것이 아니라 뒤에 noise term을 더해주어야 한다. 이를 고려하면 아래와 같이 나온다.



이 noise term은 아래와 같은 평균/분산을 가진다.



이 식을 정리하여 보면 아래와 같이 Stochastic differential equation 형태로 나오게 된다.





이제 이 확률미분방정식을 풀면 아래와 같이 나오게 된다.
  

즉, 이것이 수익율에 대한 기대값인 것이다.

확률미분방정식은 기댓값만 맞추는 개념이라고 생각하면 된다. 즉, 뒤의 noise term은 기댓값이 0이기 때문에 확률미분방정식을 풀 때는 고려하지 않는다. 그러므로 위의 형태로 식을 고칠 수 있고, 미분방정식의 가장 간단한 형태이기 때문에 저런 식으로 해를 구할 수 있다. 고등미적분학이나 미분방정식 수업을 들으면 쉽게 풀 수 있는 1차 미분방정식의 기본적인 형태이다. 하지만 수업을 안 들은 사람들을 위해서 간단히 중간 전개식을 쓰면 다음과 같다. 

