# Swap

Forward and Futures 

선도 가격은 어떻게 결정되는가? Arbitrageur 가 존재하지 않는 범위 내에서 결정된다. 이에 대한 설명은 책 102 page에 있다. 즉, arbitrage가 존재하지 않게 하는 가격이어야 한다.

Spot price : \$300
Funding cost : 5%
이런 상황 하에서 만기 1년짜리 선도 가격은?


Today Action
Cashflow

Maturity Action
Cashflow
Funding
300

Repay
-315
Buy Asset
-300



Short at 340
0

Sell
340
Total 
0

Total
25


오늘 돈을 300만큼 빌리면 1년 뒤에는 이자까지 포함해서 315만큼을 갚아야 한다. 그리고 이렇게 마련한 자금, 300을 가지고 자산을 하나를 산다. 마지막으로 이 자산을 기초 자산으로 하는 1년 뒤에 340을 주는 선도를 하나 판다. 이 것이 Arbitrage가 가능한지 알아보기 위해 만기 시점에 내가 가진 자산을 다 처분한다고 생각해 보자. 1년이 지나면 이자까지 포함해서 315만원을 갚아야 한다. 그리고 선도 계약을 통해서 1년 뒤에 내가 받을 수 있는 돈은 340이다. 이 돈을 받고 이에 해당하는 기초 자산을 하나 주면 된다. 그런데 내 수중에는 자산이 하나 있으므로, 이 것을 그냥 선도 계약 체결자에게 주기만 하면 된다. 그러면 나에게는 25만큼이 남게 되므로, Arbitrage가 발생하게 된다. 선도 가격 340이 합리적이지 않음을 알 수 있다. 그러면 어떻게 해야 합리적인 Forward Price를 계산할 수 있을까?

만약 3개월 뒤에 어떤 자산을 사길 원한다고 생각해보자. 이걸 만족시키는 방법은 두 가지가 있을 것이다. 하나는 지금 사서 3개월 동안 들고 있는 것이고, 다른 하나는 해당 자산을 기초 자산으로 하는 3개월 만기의 선도를 오늘 사면 된다. 



위의 ①은 자산을 사서 들고 있는 경우이고, ②는 선도를 사 놓는 것이다. 그리고 이 둘을 현재가치화 했을 때 그 가치가 동일해야 한다.

① Spot + PV (cost - benefit)
② PV (F0)

이를 바탕으로 를 계산해야 한다. 


Simple Case (without cashflow) [교과서 102 page 참고]

Stock (배당 없고 구매로 인한 비용 없음) : 30
Rf (2 year) : 5% (연간 5%)


Today Action
Cashflow

Maturity Action
Cashflow
Fundinf
30

Repay
-33.15513
Buy Stock
-30



Short at 35
0

Sell
35
Total
0





이 경우에도 역시 만기에 1.84487..이 남기 때문에 Riskless benefit이 생겨서 35는 선도의 가격으로 적합하지 않다. 그러므로 Arbitrageur 가 없는 선도의 균형 가격은 33.155… 가 된다.

따라서 선도 계약의 식은 다음과 같이 이자율을 사용해서 표현될 수 있다.

,   

Forward의 Arbitrageur

위에서 두 번의 예를 들어서 계속 선도를 Short 하는 것만 보아왔다. 그런데 반대의 경우도 Arbitrage가 가능하다는 사실을 쉽게 예상할 수 있다. 만약  라면, 기초자산을 하나 사고 해당 자산에 대한 선도 계약을 팔면 된다.  라면, 기초자산을 하나 팔고 이거에 대한 선도 계약을 하나 사면 된다. 그럼 Arbitrage를 할 수 있다.


Known Income [Hull 6판 page 104-106]

위의 경우에는 배당이 전혀 없는 주식을 기초 자산으로 했기 때문에 만기의 Cashflow만 보면 해결을 할 수 있었다. 이번에는 이런 만기 이전에 현금 흐름이 발생하는 경우에 대해서도 알아보도록 하자. 그 중에 첫 번째 경우로 앞으로 발생할 수익이 미리 알려질 경우의 선도 계약식이 어떻게 달라지는지 한 번 살펴보도록 하자. 주식을 기초자산으로 하는 경우에는 배당률이 계속 달라질 수 있으므로, 여기에서는 채권을 다루도록 한다.

쿠폰 지급 채권을 기초 자산으로 하는 만기 9개월짜리 선도 계약이 있다고 하자. 현재 이 채권의 가격은 $900이다. 이 채권의 만기는 9개월 이상이고, 지금으로부터 4개월 후에 $40 쿠폰을 준다고 하자. 또한 4개월 무위험 이자율은 3%, 9개월 무위험 이자율은 4%라고 한다. 

그런데 아래와 같이 Arbitrageur 가 발생하는 사례를 연구해 보고자 한다. 우선 선도 가격이 상대적으로 높은 $910이라고 하자. 이 경우 arbitrageur는 $900을 빌려서 해당 채권을 산 다음에 선도계약으로 팔아버릴 것이다. 

좀 더 자세히 알아보도록 하자. 일단 만기 이전에 발생하는 쿠폰 지급의 PV를 구해보자. 



따라서 내가 갚아야 하는 \$900 중에서 \$39.60은 쿠폰 지급을 통해서 갚아나간다고 생각할 수 있다. 남은 \$860.40은 9개월 동안 4%의 이율을 가지게 된다고 볼 수 있다. 따라서 9개월 후에 갚아야 하는 돈은 다음과 같다. 



이 값은 현재 가치가 아니라 9개월 뒤의 가치라는 것을 기억하자. 그 시점에 갚아야 하는 돈이 \$886.60인데, 그 때 선도 계약 때문에 \$910을 받게 된다. 따라서 최종적으로 Arbitrage가 발생하게 된다.



이 것을 표로 정리하면 다음과 같다. 



오늘
4개월뒤
9개월뒤
채권
\$900 채권 사기
쿠폰 \$40 발생
채권 들고 있음
선도
\$910 선도 팔기

910 받고 채권 줌
자금
\$900 빌리기
3% 이자로 돈갚기
4% 이자로 돈갚기


즉, 자금을 빌려준 사람에게 돈을 다 갚고, 사서 들고 있었던 채권으로 선도 계약자와 계약을 마무리하면 되는 것이다. 

이와 반대의 경우인 상대적으로 선도 계약금이 낮은 금액, 예를 들어 \$870에 결정되었다고 하자. 이 경우 투자자는 위와 정반대로 채권을 팔고 선도 계약을 산다. 채권을 팔은 입장에서는 4개월 뒤에 쿠폰을 줘야 하고, 9개월 뒤에는 채권을 하나 줘야 한다. 현재 채권을 팔아서 실현되는 금액 \$900 중 \$39.40은 3%짜리 4개월 대출상품에 투자하고, 이 것에 대한 이자로 채권의 쿠폰을 갚는데 쓰면 된다. 그리고 9개월 뒤에는 선도 계약으로 줘야 할 돈 \$870을 주고 채권을 받아서, 이 받은 채권으로 채권을 팔은 상대방에게 주면 된다. 그러면 다음의 Arbitrage가 발생하게 된다. 





오늘
4개월뒤
9개월뒤
채권
\$900 채권 팔기
쿠폰 \$40 주기
채권 주기
선도
\$870 선도 사기

870 주고 채권 받음
자금
채권 팔은 대금
3% 이자로 투자
4% 이자로 투자


즉, 이번에는 초기에 자금 조달 비용은 없을 수 있지만, 채권을 팔 수 있는 상황이 되어야 하고, 4개월과 9개월 만기의 상품으로 3%, 4% 이자로 투자할 수 있는 상품을 은행과 거래를 할 수 있어야 할 것이다. 복잡한 것처럼 보이기는 하지만, 선도 계약을 산다는 것과 판다는 것의 의미, 그리고 현금흐름의 특징을 잘 이해하고 있다면 조금만 생각하면 쉽게 이해할 수 있을 것이다. 


Forward and Futures contracts on Currencies

아래와 같이 변수들을 정의한다.

: The current spot price in dollars of one unit of the foreign currency 
(예를 들어 \$x = 1 won)
: Forward price in dollars of one unit of the foreign currency.
: 외환을 사용하는 국가의 무위험 이자율
: 자국(미국)의 무위험 위자율
: 투자 기간 

그럼 아래와 같은 식이 성립한다.



예제를 통해서 알아보도록 하자.

2-year interest rate in Korea : 5%
2-year interest rate in US : 7%
Spot exchange rate between won and dollar is 0.6200 US per WON.

이 경우 2-year의 Forward exchange rate은 공식에 대입해 보면 다음과 같이 나온다. 



만약 2-year의 forward exchange rate가 이것보다 작은, 예를 들어서 0.6300 이었다고 해 보자. 이 경우 Arbitrageur는 아래와 같이 할 수 있다. 

1) 1,000 Won을 5% 이율로 2년간 빌린다. 이를 620 US로 환전하고 미국 시장에 7%를 받고 투자한다.
2) 692.26 US를 주고(=1,105.17x0.63), 1,105.17 Won을 받는 선도 계약에 들어간다.

환전된 620 USD는 미국 시장에 2년 동안 투자할 경우 다음의 값을 얻을 수 있다. 



2년 뒤에 생긴 이 돈 중에 696.26 USD는 선도 계약의 대가로 주고 대신 1,105.17 Won을 받으면 된다. 이 금액은 1000Won을 한국 시장에만 투자했을 경우 2년 후 받는 금액과 정확히 같다.(1,000e0.05x2 = 1,105.17) 따라서 이 전략은 무위험 수익 713.17 - 696.26=16.91 USD를 얻게 만든다.

이 계약은 기초 자산이 2개처럼 보이지만, 사실은 기초 자산 2개를 묶어서 그 차를 하나의 자산으로 생각한다면, 처음에 분석했던 선도 계약과 동일한 계약이 되게 된다. 단, 두 나라를 동시에 고려해야 된다는 것만 살짝 고려해 주면 된다. 반대의 경우도 마찬가지다. 


Forward Contract의 가치 평가

Forward Contract의 균형 가격이 오늘과 만기 시점 모두에 대해서 net으로 0이라는 사실을 알았다. 이를 바탕으로 식을 세우면 다음과 같다. 



계약을 맺는 시점에는 현금흐름이 발생하지 않게 0으로 맞추지만, 그 이후부터는 이자율의 변동 혹은 다른 상황으로 인해 차이가 날 가능성이 생기게 된다. 그래서 위의 식으로 가치를 구한다. 


선물계약과 선도계약의 차이점 (page 109-110)

만약 이자율이 일정하고 만기가 같다면, 모든 상품에 대하여 forward price과 future price는 일치하게 된다. 하지만 실제 세계에서와 같이 이자율이 일정하지 않는다면, 선물계약과 선도 계약의 가격은 더 이상 일치할 수 없다. 예를 들어 보자. S라는 기초 자산은 이자율과의 상관 관계가 높다고 하여 보자. 만약 S가 상승하면 future position에 있는 투자자는 그 즉각 수익을 얻게 될 것이다. 반면 forward position에 있는 투자자는 그다지 영향을 받지 않게 된다. 따라서 S가 이자율에 대한 상관관계가 높을수록 future price의 가격은 forward price에 비해서 더 높게 된다.

이것 외에도 두 가격을 다르게 만들 수 있는 요인은 많다. 세금, 거래 비용, 마진 등등이 있다. 대개 future contract가 더 유동적이다.


Swap [Chapter 7]

간단하게 나타내면 아래와 같다.



Libor : 은행간 금융 거래 시 사용되는 이자율
Notional principal : 명목 원금 (이 돈 자체는 교환되지 않고, 이자만이 교환된다)


Business day convention
: 미래 금리를 swap하는 것인데, 주로 hedge를 목적으로 쓰인다.


FRN (Floating Rate Note) 변동 금리부 채권 :



Dead Floating Rate Note 
: (국고채 3년 - CD) + a



Swap 실습

A는 B에게 fixed rate 5%를 지불하고, B는 A에게 LIBOR를 지불한다고 하자. 이 경우 테이블은 아래와 같다. 6개월마다 한번이므로 1/2 해줌에 유의한다.


마지막에 100씩 더 들어온 이유는 명목 원금 때문이다. 여하튼 전체적으로는 0.45 이득 본 것을 알 수 있다. 

B 입장에서도 한 번 생각해 보자.,



이런 식으로 진행이 되어서 마지막까지 payment가 일어난다. 그런데 swap이 시작되는 날인 2003년 3월에는 미래에 금리가 어떻게 변할지 사실 아무도 모른다. 그래서 여기에 적어 둔 금리들은 여러 가지 가능한 시나리오 중에 하나일 뿐이다.

A라는 사람이 고정 금리를 지급하고, 그에 상응하는 변동 금리를 받는 경우, 이 사람은 Libor 금리가 상승하면 유리하다. 즉, 금리가 상승할거라고 예측하면 나는 고정금리를 줄 테니까 변동금리를 다오, 그럴 수 있는 것이다.

그렇다면 A라는 사람이 speculator인가? 아니다. 이 때 Swap은 변동금리 대출을 고정금리 대출로 바꿀 수 있는 효과가 있다. 만약 A라는 사람이 제조업을 하는데, 새로운 공장을 지으려면 돈이 필요하다고 하자. 그런데 이 돈을 구하려고 은행에 갔더니 변동 금리 대출밖에 안 해준다고 했다고 하자. 이 때, A는 제조업자이기 때문에 이자비용이 고정되어 있는 것이 편하다. 그래서 고정 이자율로 대출을 받고 싶은데, 은행에서는 변동으로 빌려주려고 한다. 이 때 A의 위와 같은 행동(swap)을 통해 변동금리 대출을 고정금리 대출의 형태로 바꿀 수 있다. 이런 이유로 swap이 필요한 것이다.




위와 같이 swap이 발생한다고 하자. MS의 경우, 외부에 L+0.1%를 지급(-)하고, L을 받고(+), 5%를 준다(-). 따라서 이걸 계산하면 -L-0.1+L-5 = -5.1%가 된다. 즉 전체적으로는 5.1%를 외부에 주는 효과가 나오는 것이다.

반면 Intel의 경우, 외부에 5.2%를 지급(-)하고, L을 주고(-), 5%를 받는(+)다. 따라서 이걸 몽땅 합치면 -5.2-L+5 = -L-0.2 가 된다. 즉 전체적으로는 L+0.2를 외부에 주는 효과가 나오게 된다. 

FRN을 가지고 있으면 항상 변동 금리로 수입이 생긴다. 그런데 이걸 고정금리로 하면 bond를 가지고 있는 것처럼 되는 것이다.


스왑을 이용해서 부채의 특성을 변화




회사
스왑 이전
스왑 이후
부채 변화
MS
-(6m Libor + 10bp)
-5.1%
변동금리 -> 고정금리
인텔
-5.2%
-(6m Libor + 20bp)
고정금리 -> 변동금리




스왑을 이용해서 자산의 특성을 변화




회사
스왑 이전
스왑 이후
부채 변화
MS
4.7%
6m Libor - 30bp
고정금리 -> 변동금리
인텔
6m Libor - 20bp
4.8%
변동금리 -> 고정금리



금융중개기관의 역할

비금융회사들이 직접 스왑 거래를 하는 경우는 거의 없다. 즉, 금융중개기관(은행 또는 다른 금융회사)을 통해서 거래를 하게 되는데, 금융중개기관은 중간에서 중개를 하고 3~4bp 정도를 챙긴다.



여기서 고정금리가 3bp차이나는 것을 알 수 있는데, 이 것을 은행이 가져가는 것이다. 만약 인텔과 MS로부터 같은 수수료를 받는다고 가정하면 1.5bp씩 부담하는 것이다. 


Swap의 Long과 Short

Swap도 long과 short이 있다. 누가 long이고 누가 short 인가? Swap의 Cashflow를 생각해 보자. 



위의 그림을 통해서 알 수 있듯이, Swap을 한 번 할 경우 여러 번의 현금흐름이 발생하게 되는데, 한 쪽은 계속해서 고정된 금리로, 다른 쪽은 변동 금리로 발생하게 된다. 즉, 여러 개의 만기가 다른 선도계약의 합이라고 볼 수도 있다. 여기서 선도계약의 경우를 다시 떠올려 보자. 미래의 특정시점이 되면 그 물건의 가격이 얼마가 되든지 고정된 금액을 지불하는 것을 long이라고 한다. 이 논리를 Swap에 적용시켜 보면, 고정된 금액을 제시하는 쪽이 Swap의 Long Position에 서게 되는 것이다. 그렇기 때문에 고정금리를 주고 변동금리를 받는 것을 Swap을 Long 했다고 하고, 변동금리를 주고 고정금리를 받는 것을 Swap을 Short 했다고 한다. 다르게 말하면, 기초자산이 "변동금리"인 것이다. 그런데 사실 Swap Dealer들은 이 표현을 잘 안 쓴다. 실무에 있는 사람들조차 누가 long이고 누가 short인지 헷갈리니까 그렇다. 그래서 그냥 "고정금리를 줄 테니 변동금리를 달라"라고 말한다. 

여기서 기초자산이 변동금리라면, 고정금리는 무엇인가? 바로 Swap의 가격 개념이 되는 것이다. 이것을 Swap Rate 라고 하는데, 이 개념을 잘 생각해보면 미래의 변동금리에 대한 가격을 고정금리로 표현한 것이라고 보면 된다. 

이제 Swap의 가격 결정은 곧 고정금리를 결정하는 것이라는 사실을 알았다. 그렇다면 이 가격은 어떻게 결정이 되는가? Hull 책을 보면, 비교 우위라는 내용이 있는데, 그 관계에 의해서 결정된다는 주장이 있다.  책에 있으니깐 가르치긴 한다만, 마음에 와 닿지 않는 부분이기 때문에 간략하게 하고 넘어가려고 한다. 



Competitive advantage에 의한 swap rate의 결정

A라는 사람이 있고 B라는 사람이 있다. 두 사람이 각각 은행에 갔다. 이 경우 은행은 두 사람의 신용도에 따라 이자율을 결정해서 줄 것이다. 은행이 A의 경우에는 고정금리로 돈을 빌리고자 하면 연 10%에 주고, 변동금리로 하고 싶다면 Libor+3bp로 제시했다고 하자. B에게는 고정금리 11.2%와 변동 금리 Libor+10bp를 제시했다고 하자. 당연히 A의 신용도가 더 좋은 것이다. 고정금리도 그렇고, 변동금리에서도 그렇다. 그래서 A는 B에 대해 돈을 빌리는 측면에 있어 절대 우위에 있는 것이다.



경제학입문에서 무역의 이득에 대해서 배울 때, 절대우위에 있더라도 비교우위에 있는 것을 특화할 필요가 있다고 배웠던 것을 떠올려 보자. 이 경우에도 비교우위를 한 번 떠올려 보자. B 입장에서는 고정금리 시장에서는 A보다 1.2%만 더 지불하면 되고 변동 금리에서는 0.7%만 더 지불하면 된다. 따라서 변동금리 시장에서 돈을 빌리는 것에 B가 비교우위를 가지고 있다. 

만약, A와 B모두 비교우위에 따라서 돈을 빌리고 싶은 경우를 상정해 보자. 즉, A는 고정금리고, B는 변동금리로 말이다. 이런 상황에서는 스왑이 일어날 유인이 없다. 그런데 반대의 경우에는 스왑이 일어날 유인이 있다. A의 경우 변동금리로 빌리고 싶고, B의 경우에는 고정금리로 빌리고 싶다고 하자. 그러면 Swap을 이용해서 자기가 원하는 형태로 바꿀 수 있다. 즉, A는 고정금리로 은행에 가서 돈을 빌리고, B는 변동금리로 돈을 빌려서, 둘이 서로 Swap을 하는 것이다. 그렇다면 이 경우에 swap rate를 얼마로 정하는 것이 좋겠는가?



이 때 Swap rate가 얼마일 때 A도 유리하고 B도 유리한가? Cashflow 관점에서 써 보자. 

A입장에서 나가는 돈 : -10% + x% - L 
B입장에서 나가는 돈 : -(L+1%) + L - x% = -(x%+1%) 

그런데 A, B 모두 이렇게 나가기로 한 돈과 원래 비교 우위 사이의 차액이 서로 같아야 한다고 해보자. A의 비교우위는 변동금리로 원래 L + 0.3% 이고, B의 비교우위는 고정금리로 원래 11.2 % 이다. 이걸 각각에서 빼 준 다음에 이 차이가 같도록 하면 된다.

A의 차 : -10% + x% - L + (L+0.3%)
B의 차 : -(x%+1%) + 11.2%

이 둘이 같아야 하므로 열심히 풀어서 구하면 x = 9.95%가 나온다. 이것이 이 둘 간의 Swap rate이다.



이런 경우 A, B중에서 누가 가장 손해를 보았는가? 바로 은행이다. 은행은 일종의 arbitrage를 당한 셈이다. 만약 A와 B가 서로 Swap 거래를 못 했다면, 은행에서 원하는 대로 시행됐을 것이고, 그러면 은행은 arbitrage를 안 당했을 것이다. 그런데 스왑거래를 통해서 부채의 성질을 바꿀 수 있게 되면, 서로 비교우위가 있는 쪽에서 돈을 빌리고 swap을 했기 때문에 은행은 그 금액만큼 손해를 본 것이다.

그 다음으로 손해를 본 사람은 누구인가? A이다. 단순히 생각하면 A가 원래 빌릴 수 있는 것보다 더 낮은 이자율로 빌렸는데, 왜 손해를 봤는지 이해가 안 갈 수 있다. 하지만 잘 생각해보면 A가 B보다 신용 등급이 좋은데, 은행으로부터 얻은 이익을 똑같이 분배한 것은 A의 입장에서는 손해라고 볼 수 있다. 따라서 A가 좀 더 많이 이익을 얻고, B가 좀 덜 받는 모습이 되어야 한다.