---
title: "Financial Engineering and TensorFlow"
author: "Joocheol Kim"
date: "Spring, 2021"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook: default
documentclass: book
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview {-}

금융공학, 인공지능. 두가지 모두 매력적인 말입니다.

이 두가지를 모두 배울 수 있을까요? 그것이 바로 이 강의가 추구하는 바입니다. 금융공학과 인공지능의 기초뿐만이 아니라, 수준 있는 내용까지 모두 배우고 이를 세상에 활용해 볼 수 있을 정도까지의 준비를 하는 것입니다.

이 강의는 아직도 개발 중입니다. 계속해서 새로운 내용을 추가하도록 하겠습니다.


<!--chapter:end:index.Rmd-->

# (PART) Financial Engineering {-}
# Financial Transctions

## 거래(계약)라는 것은 무엇일까?

가장 이해하기 쉬운 형태는 **사다**와 **팔다**일 것입니다. 하지만 사다와 팔다를 다른 관점으로 바라보면, **주다(pay)**와 **받다(receive)**로 해석할 수 있습니다.

```{example}


여기서 apple은 먹는 사과를 생각해도 되고, 애플 주식으로 생각해도 됩니다.

1. 1000원을 주고 apple을 사다.

2. 1000원을 받고 apple을 팔다.

3. 1000을 pay하고 apple을 receive하다

4. 1000을 receive하고 apple을 pay하다
```

## 4가지의 서로 다른 거래

pay와 receive를 시간과 함께 그려보겠습니다. $y$ 축 방향으로의 굵은 선은 apple, 보통 굵기의 선은 돈이고, 플러스 방향을 receive, 마이너스 방향을 pay로 생각하겠습니다. $x$축은 시간을 표시 합니다. $t=0$과 $t=T$이 있습니다. $T$는 우리가 지정한 특정 시점을 의미합니다. 1년 후로 생각해도 되고, 1개월 후로 생각해도 됩니다. $0$은 현재 시점입니다.


(a)
```{tikz, fig.align='center', echo=FALSE, out.width='80%'}
\begin{tikzpicture}
\draw (-1,0) -- (6,0);
\draw (0, 0.1) -- (0, -0.1) node[anchor=north west] {$0$};
\draw (5, 0.1) -- (5, -0.1) node[anchor=north west] {$T$};

\draw [->, very thick] (0,0) -- (0,1);
\draw [->] (0,0) -- (0,-1);
\end{tikzpicture}
```

(b)
```{tikz, fig.align='center', echo=FALSE, out.width='80%'}
\begin{tikzpicture}
\draw (-1,0) -- (6,0);
\draw (0, 0.1) -- (0, -0.1) node[anchor=north west] {$0$};
\draw (5, 0.1) -- (5, -0.1) node[anchor=north west] {$T$};

\draw [->, very thick] (0,0) -- (0,1);
\draw [->] (5,0) -- (5,-1);
\end{tikzpicture}
```


(c)
```{tikz, fig.align='center', echo=FALSE, out.width='80%'}
\begin{tikzpicture}
\draw (-1,0) -- (6,0);
\draw (0, 0.1) -- (0, -0.1) node[anchor=north west] {$0$};
\draw (5, 0.1) -- (5, -0.1) node[anchor=north west] {$T$};

\draw [->, very thick] (5,0) -- (5,1);
\draw [->] (0,0) -- (0,-1);
\end{tikzpicture}
```


(d)
```{tikz, fig.align='center', echo=FALSE, out.width='80%'}
\begin{tikzpicture}
\draw (-1,0) -- (6,0);
\draw (0, 0.1) -- (0, -0.1) node[anchor=north west] {$0$};
\draw (5, 0.1) -- (5, -0.1) node[anchor=north west] {$T$};

\draw [->, very thick] (5,0) -- (5,1);
\draw [->] (5,0) -- (5,-1);
\end{tikzpicture}
```

하나씩 살펴보겠습니다.

a는 우리가 일상적으로 생각하는 거래입니다. 1000을 pay하고, apple을 receive합니다.

b는현재 시점 $t=0$에 apple을 recieve하고, 미래의 특정 시점 $t=T$에 일정금액을 pay합니다. 이러한 거래는 신용을 기반으로 하는 거래로, 은행의 대출, 또는 채권(bond)이라는 금융상품과 관련이 있습니다.

```{example} 


b와 같은 형태의 거래를 예를 들어 보면,

1. 은행에서 1개월 만기 대출을 받아 apple을 사고, 1개월 후에 원금과 이자를 갚는다.

2. 1개월 만기 채권을 발행하여, 채권가격 1000으로 현재시점에서 apple을 사고, 1개월 후 채권의 소유자에게 채권의 원금이 1000과 정하여진 coupon (채권 발행시 미리 정한 이자를 의미함)을 지불한다.

3. 신용카드를 이용하여 apple을 사고, 1개월 후 신용카드 대금을 갚는다.

```


<!--chapter:end:11-financial-transactions.Rmd-->

# (PART) Financial Mathematics {-}
# Browian Motion

<!--chapter:end:21-brownian-motion.Rmd-->

# (PART) Advanced Finacial Engineering {-}
# Barrier Options

<!--chapter:end:31-barrier-options.Rmd-->

# (PART) TensorFlow {-}
# The Simplest Neural Network Ever

<!--chapter:end:41-the-simplest-neural-network.Rmd-->

# (APPENDIX) Appendix {-}
# Python 

<!--chapter:end:61-python.Rmd-->

# Linear Algebra

<!--chapter:end:71-linear-algebra.Rmd-->

# Calculus

<!--chapter:end:81-calculus.Rmd-->

# Statistics

<!--chapter:end:91-statistics.Rmd-->

